artifact_location: file:///C:/Users/HP/Desktop/LEI/3ANO/2Semestre/AOOP/TP-Computer-Vision/runs/mlflow/315779681795979557
creation_time: 1747853875801
experiment_id: '315779681795979557'
last_update_time: 1747853875801
lifecycle_stage: active
name: /Shared/Ultralytics
