artifact_location: file:///C:/Users/HP/Desktop/LEI/3ANO/2Semestre/AOOP/TP-Computer-Vision/runs/mlflow/0
creation_time: 1747853875607
experiment_id: '0'
last_update_time: 1747853875607
lifecycle_stage: active
name: Default
